version: '3'
services:
  front:
    container_name: front_playground
    build:
      context: ./front-react
      dockerfile: ../Dockerfile-react.dev
    volumes:
      - ./front-react:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - dev

networks:
  dev: